# Generated by Django 4.2.1 on 2023-05-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='public',
            options={'verbose_name': 'Public', 'verbose_name_plural': 'Publics'},
        ),
    ]
