# Generated by Django 4.2.1 on 2023-05-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_image_options_alter_public_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
